//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEGREE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEGREE()
        {
            this.EMPLOYEE = new HashSet<EMPLOYEE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> YEAR_GOT { get; set; }
        public Nullable<int> NAME_D { get; set; }
    
        public virtual DEGREELIST DEGREELIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE> EMPLOYEE { get; set; }
    }
}
